import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en:{
        'character.creator.unable.to.save': '无法保存角色，请重新加入服务器',
        'character.creator.blemishes': '瑕疵',
        'character.creator.visibility': '可见度',
        'character.creator.sun.damage': '日晒损伤',
        'character.creator.damage': '损伤',
        'character.creator.freckles': '雀斑',
        'character.creator.aging': '老化',
        'character.creator.lipstick': '口红',
        'character.creator.color': '颜色',
        'character.creator.blusher': '腮红',
        'character.creator.makeup': '化妆',
        'character.creator.blemish': '瑕疵',
        'character.creator.face.father': '父亲面部特征',
        'character.creator.face.mother': '母亲面部特征',
        'character.creator.skin.father': '父亲肤色',
        'character.creator.skin.mother': '母亲肤色',
        'character.creator.skin.mix': '肤色混合',
        'character.creator.face.mix': '面部混合',
        'character.creator.eyes': '眼睛',
        'character.creator.body.type': '体型',
        'character.creator.save': '保存',
        'character.creator.processing': '处理中...',
        'character.creator.hair': '头发',
        'character.creator.hair.color': '发色',
        'character.creator.hair.highlight': '头发高光',
        'character.creator.eyebrows': '眉毛',
        'character.creator.eyebrows.color': '眉毛颜色',
        'character.creator.facial.hair': '面部毛发',
        'character.creator.facial.color': '面部毛发颜色',
        'character.creator.category': '类别',
        'character.creator.nose.width': '鼻宽',
        'character.creator.nose.height': '鼻高',
        'character.creator.nose.length': '鼻长',
        'character.creator.nose.profile': '鼻轮廓',
        'character.creator.nose.tip': '鼻尖',
        'character.creator.nose.broke': '鼻梁',
        'character.creator.brow.height': '眉高',
        'character.creator.brow.depth': '眉深',
        'character.creator.cheek.height': '颧骨高',
        'character.creator.cheek.depth': '颧骨深',
        'character.creator.cheek.puffed': '丰颊',
        'character.creator.eyes.size': '眼睛大小',
        'character.creator.lips.size': '嘴唇大小',
        'character.creator.jaw.width': '下颌宽度',
        'character.creator.jaw.rounded': '下颌圆度',
        'character.creator.chin.height': '下巴高度',
        'character.creator.chin.depth': '下巴深度',
        'character.creator.chin.pointed': '下巴尖度',
        'character.creator.chin.dimple': '下巴酒窝',
        'character.creator.neck.size': '脖子大小'
    },
    uk: {
        'character.creator.unable.to.save': 'Не вдалося зберегти персонажа, перезапустіть гру',
        'character.creator.blemishes': 'Дефекти шкіри',
        'character.creator.visibility': 'Видимість',
        'character.creator.sun.damage': 'Загар',
        'character.creator.damage': 'Пошкодження',
        'character.creator.freckles': 'Веснянки',
        'character.creator.aging': 'Старіння',
        'character.creator.lipstick': 'Помада',
        'character.creator.color': 'Колір',
        'character.creator.blusher': 'Рум\'яна',
        'character.creator.makeup': 'Макіяж',
        'character.creator.blemish': 'Плями',
        'character.creator.face.father': 'Обличчя батька',
        'character.creator.face.mother': 'Обличчя матері',
        'character.creator.skin.father': 'Шкіра батька',
        'character.creator.skin.mother': 'Шкіра матері',
        'character.creator.skin.mix': 'Змішування шкіри',
        'character.creator.face.mix': 'Змішування обличчя',
        'character.creator.eyes': 'Очі',
        'character.creator.body.type': 'Тип тіла',
        'character.creator.save': 'Зберегти',
        'character.creator.processing': 'Обробка...',
        'character.creator.hair': 'Волосся',
        'character.creator.hair.color': 'Колір волосся',
        'character.creator.hair.highlight': 'Мелірування волосся',
        'character.creator.eyebrows': 'Брови',
        'character.creator.eyebrows.color': 'Колір брів',
        'character.creator.facial.hair': 'Волосся',
        'character.creator.facial.color': 'Колір волосся',
        'character.creator.category': 'Категорія',
        'character.creator.nose.width': 'Ширина носа',
        'character.creator.nose.height': 'Висота носа',
        'character.creator.nose.length': 'Довжина носа',
        'character.creator.nose.profile': 'Профіль носа',
        'character.creator.nose.tip': 'Кінчик носа',
        'character.creator.nose.broke': 'Зламаний ніс',
        'character.creator.brow.height': 'Висота брів',
        'character.creator.brow.depth': 'Глибина брів',
        'character.creator.cheek.height': 'Висота щік',
        'character.creator.cheek.depth': 'Глибина щік',
        'character.creator.cheek.puffed': 'Пухлісь щік',
        'character.creator.eyes.size': 'Розмір очей',
        'character.creator.lips.size': 'Розмір губ',
        'character.creator.jaw.width': 'Ширина щелепи',
        'character.creator.jaw.rounded': 'Округлість щелепи',
        'character.creator.chin.height': 'Висота підборіддя',
        'character.creator.chin.depth': 'Глибина підборіддя',
        'character.creator.chin.pointed': 'Гострота підборіддя',
        'character.creator.chin.dimple': 'Ямочки на підборідді',
        'character.creator.neck.size': 'Розмір шиї',
    },
    hu: {
        "character.creator.unable.to.save": "Nem sikerült menteni a karaktert, csatlakozz újra a szerverre",
        "character.creator.blemishes": "Hibák",
        "character.creator.visibility": "Láthatóság",
        "character.creator.sun.damage": "Nap károsítása",
        "character.creator.damage": "Kár",
        "character.creator.freckles": "Szeplők",
        "character.creator.aging": "Öregedés",
        "character.creator.lipstick": "Rúzs",
        "character.creator.color": "Szín",
        "character.creator.blusher": "Arcpirosító",
        "character.creator.makeup": "Smink",
        "character.creator.blemish": "Hiba",
        "character.creator.face.father": "Arc Apa",
        "character.creator.face.mother": "Arc Anya",
        "character.creator.skin.father": "Bőr Apa",
        "character.creator.skin.mother": "Bőr Anya",
        "character.creator.skin.mix": "Bőrkeverék",
        "character.creator.face.mix": "Arc keverék",
        "character.creator.eyes": "Szemek",
        "character.creator.body.type": "Testtípus",
        "character.creator.save": "Mentés",
        "character.creator.processing": "Feldolgozás...",
        "character.creator.hair": "Haj",
        "character.creator.hair.color": "Hajszín",
        "character.creator.hair.highlight": "Hajfény",
        "character.creator.eyebrows": "Szemöldök",
        "character.creator.eyebrows.color": "Szemöldökszín",
        "character.creator.facial.hair": "Arcszőrzet",
        "character.creator.facial.color": "Arcszőrzet színe",
        "character.creator.category": "Kategória",
        "character.creator.nose.width": "Orrszélesség",
        "character.creator.nose.height": "Orrmagasság",
        "character.creator.nose.length": "Orrhossz",
        "character.creator.nose.profile": "Orrprofil",
        "character.creator.nose.tip": "Orrhegy",
        "character.creator.nose.broke": "Összetört orr",
        "character.creator.brow.height": "Szemöldök magassága",
        "character.creator.brow.depth": "Szemöldök mélysége",
        "character.creator.cheek.height": "Pofa magassága",
        "character.creator.cheek.depth": "Pofa mélysége",
        "character.creator.cheek.puffed": "Puffadt pofa",
        "character.creator.eyes.size": "Szemek mérete",
        "character.creator.lips.size": "Ajak mérete",
        "character.creator.jaw.width": "Állkapocs szélessége",
        "character.creator.jaw.rounded": "Kerek állkapocs",
        "character.creator.chin.height": "Áll magassága",
        "character.creator.chin.depth": "Áll mélysége",
        "character.creator.chin.pointed": "Csúcsos áll",
        "character.creator.chin.dimple": "Gyűrűs áll",
        "character.creator.neck.size": "Nyak mérete"
    }    
});
