export const NotificationConfig = {
    debugMode: true,
    enableSounds: true,
    enableRebarSelector: true,
    notificationDuration: 10000,
    darkMode: false,
};

export const NotificationTypes = {
    info: 'ℹ️', 
    error: '❌',
    success: '✅',
    warning: '⚠️',
    question: '❓',
    star: '⭐',     
    heart: '❤️', 
    check: '✔️',  
    cross: '✖️',  
    up: '⬆️',     
    down: '⬇️',    
    left: '⬅️',    
    right: '➡️',  
    flag: '🚩',    
    clock: '🕒',   
    fire: '🔥',    
    thunder: '⚡', 
    snowflake: '❄️',
    book: '📖',   
    envelope: '✉️' ,
    danger: '☠️',     
    safe: '🛡️',     
    emergency: '🚨',  
    doctor: '🩺',   
    police: '👮',    
    attack: '⚔️',    
    defense: '🛡️',   
    health: '❤️',    
    money: '💰',     
    map: '🗺️',       
    quest: '📜',     
    food: '🍔',      
    drink: '🥤',     
    magic: '✨',    
    weapon: '🔫',   
    shield: '🛡️',   
    victory: '🏆',  
    defeat: '💀',    
    chat: '💬',      
    settings: '⚙️'  
}