import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'character.select.no.account': '未找到账号，请重新启动游戏',
        'character.select.bad.write': '更新失败，请重新加入服务器',
        'character.select.bad.character': '角色不存在，请重新加入服务器',
        'character.select.first.invalid': '名字无效',
        'character.select.last.invalid': '姓氏无效',
        'character.select.invalid.characters': '名字包含无效字符',
        'character.select.username.taken': '名字不可用',
        'character.select.character.not.found': '未找到角色，已刷新角色列表',
        'character.select.submit': '提交',
        'character.select.cancel': '取消',
        'character.select.confirm': '确认',
        'character.select.delete': '删除角色',
        'character.select.spawn': '创建角色外观',
        'character.select.create': '创建角色',
        'character.select.no.appearance': '还未创建角色外观',
        'character.select.confirm.delete': '确定要删除吗',
        'character.select.first': '名字',
        'character.select.last': '姓氏',
        'character.select.max.characters.reached': '已达到最大角色数'
    },
    uk: {
        'character.select.no.account': 'Акаунт не знайдено, перезапустіть гру',
        'character.select.bad.write': 'Не вдалося оновити, знову приєднайтесь до сервера',
        'character.select.bad.character': 'Персонаж не існує, знову приєднайтесь до сервера',
        'character.select.first.invalid': 'Невірне Ім\'я',
        'character.select.last.invalid': 'Невірне Прізвище',
        'character.select.invalid.characters': 'Ім\'я містить недопустимі символи',
        'character.select.username.taken': 'Ім\'я недоступне',
        'character.select.character.not.found': 'Персонаж не знайдено, оновіть персонажів',
        'character.select.submit': 'Створити',
        'character.select.cancel': 'Скасувати',
        'character.select.confirm': 'Підтвердити',
        'character.select.delete': 'Видалити',
        'character.select.spawn': 'Поява',
        'character.select.create': 'Створити персонажа',
        'character.select.no.appearance': 'Немає зовнішності',
        'character.select.confirm.delete': 'Ви впевнені, що хочете видалити',
        'character.select.first': 'Ім\'я',
        'character.select.last': 'Прізвище',
        'character.select.max.characters.reached': 'Досягнуто максимальної кількості символів',
    },
    hu: {
        "character.select.no.account": "Nem található fiók, indítsd újra a játékot",
        "character.select.bad.write": "Frissítés sikertelen, csatlakozz újra a szerverre",
        "character.select.bad.character": "A karakter nem létezik, csatlakozz újra a szerverre",
        "character.select.first.invalid": "Az keresztnév érvénytelen",
        "character.select.last.invalid": "A vezetéknév érvénytelen",
        "character.select.invalid.characters": "A név érvénytelen karaktereket tartalmaz",
        "character.select.username.taken": "A név már foglalt",
        "character.select.character.not.found": "A karakter nem található, frissítsd a karaktereket",
        "character.select.submit": "Küldés",
        "character.select.cancel": "Mégse",
        "character.select.confirm": "Megerősítés",
        "character.select.delete": "Törlés",
        "character.select.spawn": "Kiválasztás",
        "character.select.create": "Karakter Létrehozása",
        "character.select.no.appearance": "Nincs megjelenés",
        "character.select.confirm.delete": "Biztosan törölni szeretnéd",
        "character.select.first": "Keresztnév",
        "character.select.last": "Vezetéknév",
        "character.select.max.characters.reached": "Elérted a maximális karakterek számát"
    }
});
